name: 'Demo project@2'
description: 'Custome Github Action for demo'
inputs:
  message:  # id of input
    description: 'Demo message'
    required: true
    default: 'Action'
outputs:
  time: # id of output
    description: 'The time message is displayed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
